const panels={pt:{banners:{kicker:'DESTAQUES QUE ACOMPANHAM A PAUTA',title:'A página inicial no tempo da comunicação.',text:'A equipe atualiza os banners pelo painel, sem enviar cada alteração para desenvolvimento. O destaque do site passa a acompanhar as prioridades do instituto em minutos.',foot:'Atualização direta pela equipe do InovaCine'},eventos:{kicker:'DIVULGAÇÃO SEM COMPLICAÇÃO',title:'Eventos online sempre em evidência.',text:'A divulgação e a atualização dos eventos online ficam centralizadas no painel. A equipe mantém as informações e os destaques alinhados à programação do instituto.',foot:'Mais agilidade para comunicar a programação'},materias:{kicker:'AUTONOMIA EDITORIAL',title:'Da pauta à matéria publicada.',text:'O gerenciamento das matérias permite que a equipe mantenha o blog atualizado. A publicação do conteúdo editorial passa a fazer parte da rotina de comunicação, sem depender de alterações no código.',foot:'Conteúdo publicado por quem cuida da comunicação'}},en:{banners:{kicker:'HIGHLIGHTS THAT FOLLOW THE AGENDA',title:'The homepage on communication time.',text:'The team updates banners from the panel without sending each change to development. The site highlight stays aligned with the institute\'s priorities in minutes.',foot:'Direct update by the InovaCine team'},eventos:{kicker:'DISCLOSURE WITHOUT COMPLICATIONS',title:'Online events always in focus.',text:'Promoting and updating online events is centralized in the panel. The team keeps information and highlights aligned with the institute\'s schedule.',foot:'More agility to communicate programming'},materias:{kicker:'EDITORIAL AUTONOMY',title:'From agenda to published article.',text:'Article management allows the team to keep the blog updated. Publishing editorial content becomes part of the communication routine, without depending on code changes.',foot:'Content published by those who handle communications'}}};
const tabs=[...document.querySelectorAll('[role="tab"]')];
function selectTab(button){const p=panels[currentLanguage][button.dataset.key];tabs.forEach(t=>{const active=t===button;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1});document.getElementById('panel').setAttribute('aria-labelledby',button.id);for(const key of ['kicker','title','text','foot'])document.getElementById('panel-'+key).textContent=p[key]}
tabs.forEach((button,index)=>{button.addEventListener('click',()=>selectTab(button));button.addEventListener('keydown',event=>{let next=index;if(event.key==='ArrowDown')next=(index+1)%tabs.length;else if(event.key==='ArrowUp')next=(index+tabs.length-1)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();tabs[next].focus();selectTab(tabs[next])})});
const flows={pt:{before:[['Enviar os layouts','A equipe encaminha a demanda ao desenvolvedor.'],['Aguardar a agenda','A publicação depende da disponibilidade técnica.'],['Receber a atualização','O fluxo completo leva de 1 a 2 dias.']],after:[['Acessar o painel','A equipe entra na área administrativa.'],['Atualizar o conteúdo','Edita o destaque conforme a pauta.'],['Publicar','Conclui a atualização em minutos.']]},en:{before:[['Send layouts','The team forwards the request to the developer.'],['Wait for schedule','Publishing depends on technical availability.'],['Receive the update','The entire flow takes 1 to 2 days.']],after:[['Access the panel','The team enters the admin area.'],['Update content','Edits the highlight according to the agenda.'],['Publish','Completes the update in minutes.']]}};

let currentLanguage=localStorage.getItem('language')||'pt';

function setLanguage(lang){currentLanguage=lang;localStorage.setItem('language',lang);document.documentElement.lang=lang;document.documentElement.setAttribute('data-lang',lang);const toggle=document.getElementById('lang-toggle');if(toggle){toggle.setAttribute('aria-pressed',String(lang==='en'));toggle.textContent=lang==='en'?'PT '+' /  EN':'PT '+' /  EN';toggle.classList.toggle('active',lang==='en')}document.querySelectorAll('[data-pt]').forEach(el=>{const pt=el.getAttribute('data-pt');const en=el.getAttribute('data-en');if(pt&&en){el.textContent=lang==='pt'?pt:en}});document.querySelectorAll('[data-pt-alt]').forEach(el=>{const pt=el.getAttribute('data-pt-alt');const en=el.getAttribute('data-en-alt');if(pt&&en){el.alt=lang==='pt'?pt:en}});document.querySelectorAll('h1[data-pt]').forEach(el=>{el.innerHTML=lang==='pt'?el.getAttribute('data-pt'):el.getAttribute('data-en')});document.querySelectorAll('h2[data-pt]').forEach(el=>{el.innerHTML=lang==='pt'?el.getAttribute('data-pt'):el.getAttribute('data-en')});updatePanelContent();updateFlowContent()}

function updatePanelContent(){const key=document.querySelector('[role="tab"][aria-selected="true"]')?.dataset.key||'banners';const p=panels[currentLanguage][key];for(const field of['kicker','title','text','foot']){const el=document.getElementById('panel-'+field);if(el)el.innerHTML=p[field]}}

function updateFlowContent(){const state=document.querySelector('[data-flow].selected')?.dataset.flow||'after';const flowData=flows[currentLanguage][state];const flow=document.getElementById('flow');if(flow&&flowData){flow.replaceChildren(...flowData.map(([title,text],i)=>{const li=document.createElement('li');const number=document.createElement('span');number.textContent='0'+(i+1);const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=text;li.append(number,h,p);return li}))}const noteEl=document.getElementById('flow-note');if(noteEl){const key=state==='before'?'pt-default':'en-default';noteEl.textContent=state==='before'?currentLanguage==='pt'?'A atualização passa por uma fila externa à equipe de comunicação.':'The update goes through an external queue outside the communications team.':currentLanguage==='pt'?'A operação acontece com a própria equipe, sem uma etapa de desenvolvimento a cada atualização.':'The operation happens with the team itself, with no development step for each update.'}}

document.addEventListener('DOMContentLoaded',()=>{setLanguage(currentLanguage);const toggle=document.getElementById('lang-toggle');if(toggle){toggle.addEventListener('click',()=>{setLanguage(currentLanguage==='pt'?'en':'pt')})}document.querySelectorAll('[data-flow]').forEach(button=>button.addEventListener('click',()=>{const state=button.dataset.flow;document.querySelectorAll('[data-flow]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button))});updateFlowContent()}))});
